"""
SamvadGenerator — handles name extraction and hobby discovery question.

"""

import nltk
from nltk.chunk import ne_chunk
from nltk.tag import pos_tag
from nltk.tokenize import word_tokenize

for _res, _path in [
    ("punkt",             "tokenizers/punkt"),
    ("maxent_ne_chunker", "chunkers/maxent_ne_chunker"),
    ("words",             "corpora/words"),
    ("averaged_perceptron_tagger", "taggers/averaged_perceptron_tagger"),
]:
    try:
        nltk.data.find(_path)
    except LookupError:
        nltk.download(_res, quiet=True)


class SamvadGenerator:
    """
    Handles name extraction from free-form speech and
    hobby discovery question generation.
    Opening questions are generated by Claude in user_info.py.
    """

    _TITLE_EXPANSIONS = {
        "dr": "Doctor", "dr.": "Doctor", "doctor": "Doctor",
        "mr": "Mister", "mr.": "Mister", "mister": "Mister",
        "mrs": "Missus", "mrs.": "Missus",
        "miss": "Miss", "ms": "Miss", "ms.": "Miss",
        "prof": "Professor", "prof.": "Professor", "professor": "Professor",
        "sir": "Sir", "madam": "Madam", "madame": "Madame",
        "rev": "Reverend", "rev.": "Reverend", "reverend": "Reverend",
        "capt": "Captain", "capt.": "Captain", "captain": "Captain",
    }

    _INTRO_PATTERNS = [
        "my name is ", "i am ", "i'm ", "this is ", "call me ",
        "hi i am ", "hi i'm ", "hello i am ", "hello i'm ",
        "hey i am ", "hey i'm ", "hi my name is ", "hello my name is ",
        "hey my name is ", "myself ", "hi myself", "hey myself",
        "hello myself", "this is", "here is", "meet", "introducing",
        "let me introduce", "allow me to introduce",
        "here we have with us", "please welcome", "say hello to",
        "allow me to introduce you to", "welcome", "we have here with us",
    ]

    def extract_name(self, input_text: str) -> str:
        """
        Extract a person's name from free-form introductory speech.
        Returns 'Friend' if no name can be identified.
        """
        if not input_text:
            return "Friend"

        text = input_text.lower().strip()

        for pattern in self._INTRO_PATTERNS:
            if pattern in text:
                name_part = text.split(pattern, 1)[1].strip()
                tokens    = word_tokenize(name_part)
                tagged    = pos_tag(tokens)

                # title + name
                if tokens and tokens[0].lower() in self._TITLE_EXPANSIONS:
                    title        = self._TITLE_EXPANSIONS[tokens[0].lower()]
                    proper_nouns = []
                    for tok, tag in tagged[1:]:
                        if tag.startswith("NNP") or (not proper_nouns and tag.startswith("NN")):
                            proper_nouns.append(tok)
                        elif proper_nouns:
                            break
                    if proper_nouns:
                        return f"{title} {' '.join(w.capitalize() for w in proper_nouns)}"
                    if len(tokens) > 1:
                        return f"{title} {tokens[1].capitalize()}"
                    return title

                # NER person entity
                chunks  = ne_chunk(tagged)
                persons = [
                    " ".join(c[0] for c in chunk)
                    for chunk in chunks
                    if hasattr(chunk, "label") and chunk.label() == "PERSON"
                ]
                if persons:
                    return persons[0].title()

                # proper nouns
                proper = [tok for tok, tag in tagged if tag.startswith("NNP")]
                if proper:
                    return " ".join(w.capitalize() for w in proper)
                if tokens:
                    return tokens[0].capitalize()

        # no intro pattern — try direct NER
        tokens = word_tokenize(text)
        tagged = pos_tag(tokens)

        for i, (tok, tag) in enumerate(tagged):
            if tok.lower() in self._TITLE_EXPANSIONS and i < len(tagged) - 1:
                nxt_tok, nxt_tag = tagged[i + 1]
                if nxt_tag.startswith("NNP") or nxt_tag.startswith("NN"):
                    return f"{self._TITLE_EXPANSIONS[tok.lower()]} {nxt_tok.capitalize()}"
                return self._TITLE_EXPANSIONS[tok.lower()]

        chunks  = ne_chunk(tagged)
        persons = [
            " ".join(c[0] for c in chunk)
            for chunk in chunks
            if hasattr(chunk, "label") and chunk.label() == "PERSON"
        ]
        if persons:
            return persons[0].title()

        proper = []
        for tok, tag in tagged:
            if tag.startswith("NNP"):
                proper.append(tok)
            elif proper:
                break
        if proper:
            return " ".join(w.capitalize() for w in proper)

        return "Friend"

    def generate_hobby_discovery_question(self, name: str, client=None) -> str:
        """
        Generate a hobby discovery question.
        Uses Claude if available, falls back to a clean default.
        """
        if client is not None:
            try:
                response = client.messages.create(
                    model="claude-3-haiku-20240307",
                    max_tokens=60,
                    messages=[{
                        "role": "user",
                        "content": (
                            f"Generate one natural, professional question to ask {name} "
                            "about their hobbies or interests outside of work. "
                            "8-15 words. Warm but not casual. Return only the question."
                        )
                    }]
                )
                q = response.content[0].text.strip().strip('"')
                if q and "?" in q:
                    return q
            except Exception:
                pass

        # clean fallback — no "Mind sharing" or informal phrasing
        fallbacks = [
            f"{name}, what do you enjoy doing outside of work?",
            f"Outside of your professional life, what interests you, {name}?",
            f"{name}, what activities or interests do you pursue in your personal time?",
            f"I'd love to know what you enjoy doing beyond your work, {name}.",
        ]
        import random
        return random.choice(fallbacks)